### ISSUE TITLE
Add "erase" or "delete"

### ISSUE THREAD

**Issue by kjcole** [MycroftAI/skill-audio-record#1]
I was listening to the news, when in the middle of it Mycroft started saying something. Since the news was on, I didn't hear Mycroft completely and did not understand what was said, but clearly the news triggered it. 
Several minutes later I heard "Stopping audio recording".

So, now I need to dig into the config, find the filename of a recording I didn't ask for, and delete it.

There should be a way to "erase" the tape from within skill-audio-record. (Or documentation on how to do it if one of the other commands has that effect.)

**Comment by augustnmonteiro** [comment]
@kjcole fixed by #2 : D, thanks for the reporting!
