### ISSUE TITLE
Asking to record for 10 seconds throws a Python integer error

### ISSUE THREAD

**Issue by KathyReid** [MycroftAI/skill-audio-record#16]
## Description of error in object-deviation format

When asking the Audio Record Skill to record for 10 seconds, it throws the error: 

```python
~~~~ - ERROR - Exception in pronounce_number_en: {}ValueError("invalid literal for int() with base 10: '.0'",)
```
I was able to replicate this error: 

![screenshot from 2018-12-26 15-22-20](https://user-images.githubusercontent.com/114158/50434596-e7e36e00-0931-11e9-9734-8e617e2838b4.png)

Specifically, the symptoms are: 

* if the Utterance `start recording for 10 seconds` is sent, this triggers the errror, _and_ the recording starts for nine seconds, **not** ten seconds. 
* if the Utterance `start recording for ten seconds` (ie using `ten` not `10`) then the audio records for one minute (the default)

Digging a little deeper into this, the function that is causing the error is `pronounce_number_en` in the file `format_en.py` [link](https://github.com/MycroftAI/mycroft-core/blob/02b8718a5b2b2174532e1411e8b7480ef23632e0/mycroft/util/lang/format_en.py#L225) which is part of `mycroft-core` itself. 

What I haven't been able to determine yet is whether the error is triggered when the Skill calculates the duration to record for, _or_ when the feedback is provided to the user about how long the recording is for. 

I **suspect** there is a bug in the `nice_duration()` function of the Audio Record Skill [link](https://github.com/MycroftAI/skill-audio-record/blob/6314b580876891b60f2f5f2a4302bebdf3824b15/__init__.py#L227) specifically because of this line of code:

`seconds = int(duration % 60)`

Ten seconds modulo 60 rounds down to integer zero.

**Comment by forslund** [comment]
I've been looking at this a bit and it seems to be unrelated to the recording skill, the error messages are produced before the skill handler is called. Seems to be when the text is normalized before sent to adapt.

**Comment by forslund** [comment]
Ok the error message isn't a real issue, everything works even though the error message is thrown. The pronounce_number is called (weirdly enough) during the intent parsing, the error message is thrown when trying to parse `10.0` as a year. (it tries this if the string representation is 4 characters). A PR for handling this more gracefully has been opened against mycroft core ([Here](https://github.com/MycroftAI/mycroft-core/pull/1916))

**Comment by forslund** [comment]
Closing this one.
